version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    environment:
      SECRET_KEY_BASE_DUMMY: "1"
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
